### ISSUE TITLE
Service Discovery 🛑

### ISSUE THREAD

**Issue by jlsan92** [strvcom/terraform-aws-fargate#29]
We're missing one important part of any Docker runtime cluster ⚠️Service Discovery!!!.

The good thing is that this core part could be easily implemented using Route53 and private namespaces. But I'm thinking about how we should implement this feature in terms of DNS records. Fargate supports both A and SRV records. Probably the way to go is multivalue A records 🤔 since every Fargate instance should be a single Docker container. 

Let's brainstorm a little 😄

**Comment by robertrossmann** [comment]
We might want to include @thunderball1 in the discussion as well. 🤔 💯
